apiVersion: v1
kind: ServiceAccount
metadata:
  name: super
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: super-user-role-binding
subjects:
- kind: ServiceAccount
  # Reference to upper's `metadata.name`
  name: super
  # Reference to upper's `metadata.namespace`
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
    app: best-fit-scheduler
  name: best-fit-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: best-fit-scheduler
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        app: best-fit-scheduler
        version: second
    spec:
      serviceAccountName: super
      containers:
      - name: best-fit-scheduler
        #image: mirrorgooglecontainers/kube-scheduler:v1.10.2
        image: moule3053/kube-scheduler:latest
        command: [/usr/local/bin/kube-scheduler,
                  --address=0.0.0.0,
                  --scheduler-name=best-fit-scheduler,
                  --policy-configmap=scheduler-config,
                  --policy-configmap-namespace=kube-system,
                  --leader-elect=false]
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10251
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10251
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts: []
      hostNetwork: false
      hostPID: false
